name: pytorch-tutorial
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy
      - torch
      - torchvision
      - torchaudio --index-url https://download.pytorch.org/whl/cu124
      - scipy
      - scikit-learn
      - matplotlib
      - seaborn
      - tqdm
      - ipykernel