name: check-format

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  check-python-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Python format
        uses: chartboost/ruff-action@v1
        with:
          args: format --check